/**
 * Cross-checks every TypeScript port against golden fixtures generated by the
 * Python projects (`site/scripts/generate_demo_data.py`).
 *
 * The demos re-implement logic that already exists in Python, which risks the
 * two quietly disagreeing. These tests make a divergence a failure.
 */

import { describe, expect, it } from "vitest";

import advisorGolden from "../../data/demos/advisor-golden.json";
import cardsGolden from "../../data/demos/cards-golden.json";
import coursesGolden from "../../data/demos/courses-golden.json";

import factorGolden from "../../data/demos/factor-golden.json";
import prices from "../../data/demos/factor-prices.json";
import rankingGolden from "../../data/demos/ranking-golden.json";
import searchIndexData from "../../data/demos/search-index.json";
import solverGolden from "../../data/demos/solver-golden.json";
import trieGolden from "../../data/demos/trie-golden.json";

import {
  type Card,
  type HandRank,
  type Rank,
  type Suit,
  HAND_SCORES,
  mulberry32,
  scoreCards,
} from "./cards";
import {
  allDiscards,
  bestDiscards,
  evaluateDiscard,
  parseCard,
  statisticalTies,
  unseenCards,
} from "./advisor";
import {
  type FactorName,
  type PriceData,
  performanceMetrics,
  runBacktest,
  zscore,
} from "./factor";
import { LruCache } from "./lru";
import {
  CATALOG,
  DEFAULT_QUARTER,
  QUARTERS,
  quarterBySlug,
  scheduledCourses,
} from "./quarters";
import {
  type Course,
  type Preferences,
  baseCode,
  coursesConflict,
  daysUsed,
  gapMinutes,
  meetingsOverlap,
  normaliseCode,
  searchByCode,
  searchSchedules,
  sectionOf,
  sectionsByCourse,
  solveSchedules,
} from "./schedule";
import {
  Trie,
  bm25Score,
  buildIndex,
  characterToKey,
  expandToken,
  inverseDocumentFrequency,
  rank,
  searchIndex,
} from "./trie";

// --------------------------------------------------------------------------- //
// Trie
// --------------------------------------------------------------------------- //

describe("trie", () => {
  const trie = new Trie(
    Object.fromEntries(trieGolden.words.map((w) => [w, `https://example.com/${w}`])),
  );

  it("matches the Python on every prefix query", () => {
    for (const [query, expected] of Object.entries(trieGolden.prefix)) {
      expect([...trie.keysWithPrefix(query)].sort()).toEqual(expected);
    }
  });

  it("matches the Python on every wildcard query", () => {
    for (const [query, expected] of Object.entries(trieGolden.wildcard)) {
      const got = [...trie.wildcardSearch(query)].map(([k]) => k).sort();
      expect(got).toEqual(expected);
    }
  });

  it("holds every word", () => {
    expect(trie.size).toBe(trieGolden.words.length);
    expect([...trie.keys()].sort()).toEqual([...trieGolden.words].sort());
  });

  it("folds letters case-insensitively and everything else into one bucket", () => {
    expect(characterToKey("a")).toBe(0);
    expect(characterToKey("A")).toBe(0);
    expect(characterToKey("z")).toBe(25);
    for (const c of ["1", " ", "-", "'"]) expect(characterToKey(c)).toBe(26);
  });

  it("rejects a multi-character input", () => {
    expect(() => characterToKey("ab")).toThrow();
  });

  it("does not treat a prefix of a key as a key", () => {
    expect(trie.has("par")).toBe(false);
    expect(trie.has("park")).toBe(true);
  });

  it("reports the walked path for the visualisation", () => {
    expect(trie.pathFor("par")).toHaveLength(4); // root + p + a + r
    expect(trie.pathFor("zzz")).toHaveLength(1); // root only
  });
});

// --------------------------------------------------------------------------- //
// Card scoring
// --------------------------------------------------------------------------- //

describe("card scoring", () => {
  it("matches the Python on all 400 golden hands", () => {
    let checked = 0;
    for (const testCase of cardsGolden.cases) {
      const hand = testCase.hand.map((c) => ({
        suit: c.suit as Suit,
        rank: c.rank as Rank,
      }));
      expect(scoreCards(hand)).toBe(testCase.rank);
      checked += 1;
    }
    expect(checked).toBe(400);
  });

  it("agrees with the Python point table", () => {
    for (const testCase of cardsGolden.cases.slice(0, 50)) {
      expect(HAND_SCORES[scoreCards(
        testCase.hand.map((c) => ({ suit: c.suit as Suit, rank: c.rank as Rank })),
      )]).toBe(testCase.points);
    }
  });

  const hand = (...specs: string[]): Card[] => {
    const suits: Record<string, Suit> = {
      C: "clubs", D: "diamonds", H: "hearts", S: "spades",
    };
    return specs.map((s) => ({
      suit: suits[s.slice(-1)],
      rank: s.slice(0, -1) as Rank,
    }));
  };

  it("scores a six-card flush, which the original missed", () => {
    expect(scoreCards(hand("2H", "4H", "6H", "8H", "10H", "QH", "3S"))).toBe("Flush");
  });

  it("scores two triples as a full house, which the original missed", () => {
    expect(scoreCards(hand("2H", "2S", "2C", "5H", "5S", "5C", "9D"))).toBe("FullHouse");
  });

  it("scores an empty hand as nothing", () => {
    expect(scoreCards([])).toBe("None");
  });
});

// --------------------------------------------------------------------------- //
// Schedule conflicts
// --------------------------------------------------------------------------- //

describe("schedule", () => {
  const courses = DEFAULT_QUARTER.courses;
  const byCode = new Map(courses.map((c) => [c.code, c]));

  it("matches the Python on every course pair", () => {
    expect(coursesGolden.pairs.length).toBeGreaterThan(300);
    for (const pair of coursesGolden.pairs) {
      const a = byCode.get(pair.a)!;
      const b = byCode.get(pair.b)!;
      expect(coursesConflict(a, b)).toBe(pair.conflicts);
    }
  });

  it("treats back-to-back meetings as compatible", () => {
    expect(
      meetingsOverlap({ day: 0, start: 1080, end: 1170 }, { day: 0, start: 1170, end: 1260 }),
    ).toBe(false);
  });

  it("treats overlapping meetings on the same day as a conflict", () => {
    expect(
      meetingsOverlap({ day: 0, start: 1050, end: 1230 }, { day: 0, start: 1080, end: 1170 }),
    ).toBe(true);
  });

  it("ignores the same hours on different days", () => {
    expect(
      meetingsOverlap({ day: 0, start: 1080, end: 1170 }, { day: 1, start: 1080, end: 1170 }),
    ).toBe(false);
  });

  it("searches by prefix, not substring", () => {
    const hits = searchByCode(courses, "530");
    expect(hits.length).toBeGreaterThan(0);
    for (const c of hits) expect(c.code.split(" ")[1].startsWith("530")).toBe(true);
    // "112" sits inside "MPCS 53112-1" but is not a prefix of the number.
    expect(searchByCode(courses, "112")).toEqual([]);
  });
});

// --------------------------------------------------------------------------- //
// Factor backtest
// --------------------------------------------------------------------------- //

describe("factor backtest", () => {
  /**
   * The shipped price file spans a wide universe and a long window; the
   * fixtures pin a fixed slice of it, so widening the data does not silently
   * invalidate them.
   */
  const goldenSlice = (): PriceData => {
    const from = prices.dates.findIndex((d) => d >= factorGolden.start);
    const to = prices.dates.findIndex((d) => d >= factorGolden.end);
    const end = to === -1 ? prices.dates.length : to;
    return {
      dates: prices.dates.slice(from, end),
      tickers: factorGolden.tickers,
      closes: Object.fromEntries(
        factorGolden.tickers.map((t) => [
          t,
          (prices.closes as Record<string, number[]>)[t].slice(from, end),
        ]),
      ),
    };
  };

  it("reproduces every golden case from the Python", () => {
    const slice = goldenSlice();
    for (const expected of factorGolden.cases) {
      const result = runBacktest(slice, {
        factors: expected.factors as FactorName[],
        topN: expected.top_n,
        rebalanceEvery: expected.rebalance_every,
        initialCash: factorGolden.initial_cash,
      });
      const metrics = performanceMetrics(result.nav);

      expect(result.rebalanceCount).toBe(expected.rebalances);
      // Floating-point accumulation differs slightly across languages.
      expect(metrics.totalReturn).toBeCloseTo(expected.total_return, 4);
      expect(metrics.sharpeRatio).toBeCloseTo(expected.sharpe_ratio, 3);
      expect(metrics.maxDrawdown).toBeCloseTo(expected.max_drawdown, 4);
    }
  });

  it("tracks the Python's NAV path, not just its endpoints", () => {
    const expected = factorGolden.cases[0];
    const result = runBacktest(goldenSlice(), {
      factors: expected.factors as FactorName[],
      topN: expected.top_n,
      rebalanceEvery: expected.rebalance_every,
      initialCash: factorGolden.initial_cash,
    });
    const sampled = result.nav.filter((_, i) => i % 50 === 0);
    expect(sampled).toHaveLength(expected.nav_samples.length);
    sampled.forEach((value, i) => {
      expect(value).toBeCloseTo(expected.nav_samples[i], 2);
    });
  });

  it("starts at the initial cash", () => {
    const result = runBacktest(goldenSlice(), {
      factors: ["momentum"], topN: 3, rebalanceEvery: 21, initialCash: 100000,
    });
    expect(result.nav[0]).toBeCloseTo(100000, 6);
  });

  it("look-ahead mode beats the honest backtest on this universe", () => {
    const options = {
      factors: ["momentum"] as FactorName[],
      topN: 2, rebalanceEvery: 21, initialCash: 100000,
    };
    const slice = goldenSlice();
    const honest = performanceMetrics(runBacktest(slice, options).nav);
    const cheating = performanceMetrics(
      runBacktest(slice, { ...options, lookAhead: true }).nav,
    );
    // The whole point of the demo: seeing the future pays.
    expect(cheating.totalReturn).toBeGreaterThan(honest.totalReturn);
  });

  it("ships a universe wide enough for factor rotation to matter", () => {
    expect(prices.tickers.length).toBeGreaterThanOrEqual(40);
    expect(prices.dates.length).toBeGreaterThan(1000);
    for (const t of prices.tickers) {
      expect((prices.closes as Record<string, number[]>)[t]).toHaveLength(
        prices.dates.length,
      );
    }
  });

  it("z-scores a flat cross-section to zero rather than NaN", () => {
    const flat = zscore(new Map([["a", 5], ["b", 5]]));
    expect([...flat.values()]).toEqual([0, 0]);
  });

  it("rejects a NAV series too short to measure", () => {
    expect(() => performanceMetrics([100])).toThrow();
  });
});

// --------------------------------------------------------------------------- //
// LRU
// --------------------------------------------------------------------------- //

describe("lru cache", () => {
  const identity = (k: string) => k;

  it("evicts the least recently used key", () => {
    const cache = new LruCache(3);
    for (const k of ["a", "b", "c"]) cache.call(k, identity);
    const event = cache.call("d", identity);
    expect(event.evicted).toBe("a");
    expect(cache.order).toEqual(["b", "c", "d"]);
  });

  it("a hit protects a key from the next eviction", () => {
    const cache = new LruCache(3);
    for (const k of ["a", "b", "c"]) cache.call(k, identity);
    cache.call("a", identity);
    expect(cache.call("d", identity).evicted).toBe("b");
  });

  it("counts hits and misses", () => {
    const cache = new LruCache(10);
    cache.call("a", identity);
    cache.call("a", identity);
    expect([cache.hits, cache.misses]).toEqual([1, 1]);
    expect(cache.hitRate).toBeCloseTo(0.5);
  });

  it("never exceeds its size", () => {
    const cache = new LruCache(4);
    for (let i = 0; i < 50; i++) cache.call(String(i), identity);
    expect(cache.size).toBe(4);
  });

  it("caches nothing at size zero but still counts", () => {
    const cache = new LruCache(0);
    cache.call("a", identity);
    cache.call("a", identity);
    expect(cache.misses).toBe(2);
    expect(cache.size).toBe(0);
  });

  it("reports a zero hit rate before any call", () => {
    expect(new LruCache(4).hitRate).toBe(0);
  });
});

describe("BM25 ranking", () => {
  const golden = rankingGolden as {
    lengths: Record<string, number>;
    postings: Record<string, Record<string, number>>;
    cases: {
      terms: string[];
      requireAll: boolean;
      hits: { url: string; score: number; matched: Record<string, number> }[];
    }[];
  };
  const corpus = { lengths: golden.lengths };

  it("agrees with the Python on every scored query", () => {
    for (const testCase of golden.cases) {
      const postings = Object.fromEntries(
        testCase.terms
          .filter((t) => t in golden.postings)
          .map((t) => [t, golden.postings[t]]),
      );
      const hits = rank(postings, corpus, testCase.requireAll);
      expect(hits.map((h) => h.url)).toEqual(testCase.hits.map((h) => h.url));
      hits.forEach((hit, i) => {
        // Scores, not just order: a port can be wrong by a hair and still
        // produce the same ranking, which is the drift worth catching.
        expect(hit.score).toBeCloseTo(testCase.hits[i].score, 6);
        expect(hit.matched).toEqual(testCase.hits[i].matched);
      });
    }
  });

  it("uses the smoothed IDF, which stays positive where Robertson's goes negative", () => {
    // The `1 +` inside the log is doing this, not the max(): "city" on 3 of 4
    // pages scores positive here and negative under the original form. An
    // earlier version of this test credited the floor, and passed for the
    // wrong reason -- the floor is unreachable for any df <= N.
    const robertson = (n: number, df: number) =>
      Math.log((n - df + 0.5) / (df + 0.5));

    for (const [n, df] of [[4, 3], [100, 99], [10, 6]] as const) {
      expect(robertson(n, df)).toBeLessThan(0);
      expect(inverseDocumentFrequency(n, df)).toBeGreaterThan(0);
    }
  });

  it("floors the IDF only when the index claims more pages than the corpus has", () => {
    // The one case max(…, 0) exists for: df > N means the index and the
    // corpus disagree, and the raw value really is negative.
    expect(inverseDocumentFrequency(10, 11)).toBe(0);
    expect(inverseDocumentFrequency(10, 20)).toBe(0);
  });

  it("never scores a golden hit negative", () => {
    for (const testCase of golden.cases) {
      for (const hit of testCase.hits) expect(hit.score).toBeGreaterThanOrEqual(0);
    }
  });

  it("requireAll turns the query from OR into AND", () => {
    const or = rank(
      { park: golden.postings.park, dog: golden.postings.dog },
      corpus,
      false,
    );
    const and = rank(
      { park: golden.postings.park, dog: golden.postings.dog },
      corpus,
      true,
    );
    expect(and.length).toBeLessThan(or.length);
    expect(and.every((h) => Object.keys(h.matched).length === 2)).toBe(true);
  });

  it("returns nothing for an empty query or an empty corpus", () => {
    expect(rank({}, corpus)).toEqual([]);
    expect(rank({ park: golden.postings.park }, { lengths: {} })).toEqual([]);
  });

  it("saturates term frequency rather than scaling with it", () => {
    // Doubling occurrences must not double the score, or one keyword-stuffed
    // page outranks everything.
    const once = bm25Score(1, 100, 100, 1);
    const ten = bm25Score(10, 100, 100, 1);
    const hundred = bm25Score(100, 100, 100, 1);
    expect(ten).toBeGreaterThan(once);
    expect(hundred).toBeGreaterThan(ten);
    expect(hundred).toBeLessThan(once * 3);
  });

  it("penalises a long page for its length without erasing it", () => {
    const short = bm25Score(3, 50, 100, 1);
    const long = bm25Score(3, 400, 100, 1);
    expect(short).toBeGreaterThan(long);
    expect(long).toBeGreaterThan(0);
  });
});

describe("the schedule solver", () => {
  const golden = solverGolden as {
    cases: {
      name: string;
      size: number;
      required: string[];
      among: string[] | null;
      preferences: Preferences;
      provenOptimal: boolean;
      options: {
        codes: string[];
        cost: number;
        breakdown: Record<string, number>;
        gapMinutes: number;
        daysUsed: number[];
      }[];
    }[];
  };
  const catalog = DEFAULT_QUARTER.courses;

  it("agrees with the Python on every scenario", () => {
    for (const testCase of golden.cases) {
      const result = searchSchedules(catalog, testCase.size, {
        required: testCase.required,
        among: testCase.among,
        preferences: testCase.preferences,
        limit: 5,
        nodeBudget: 1e9,
      });
      // The whole answer, not just the first row: a bound that loses the
      // optimum still returns a plausible schedule.
      expect(
        result.options.map((o) => o.courses.map((c) => c.code)),
        testCase.name,
      ).toEqual(testCase.options.map((o) => o.codes));
      expect(result.provenOptimal, testCase.name).toBe(testCase.provenOptimal);
      result.options.forEach((option, i) => {
        expect(option.cost, testCase.name).toBeCloseTo(testCase.options[i].cost, 6);
        expect(option.breakdown, testCase.name).toEqual(
          testCase.options[i].breakdown,
        );
        expect(gapMinutes(option.courses), testCase.name).toBe(
          testCase.options[i].gapMinutes,
        );
        expect(daysUsed(option), testCase.name).toEqual(
          testCase.options[i].daysUsed,
        );
      });
    }
  });

  it("never returns a schedule that double-books or repeats a course", () => {
    for (const option of solveSchedules(catalog, 3, { limit: 20 })) {
      const codes = option.courses;
      for (let i = 0; i < codes.length; i++) {
        for (let j = i + 1; j < codes.length; j++) {
          expect(coursesConflict(codes[i], codes[j])).toBe(false);
          expect(baseCode(codes[i])).not.toBe(baseCode(codes[j]));
        }
      }
    }
  });

  it("splits a code into its base and section", () => {
    const course = catalog.find((c) => c.code === "MPCS 55001-2")!;
    expect(baseCode(course)).toBe("MPCS 55001");
    expect(sectionOf(course)).toBe("2");
    expect(normaliseCode("mpcs 55001-2")).toBe("MPCS 55001");
  });

  it("groups sections under one course", () => {
    const groups = sectionsByCourse(catalog);
    expect(groups.get("MPCS 55001")!.map((c) => c.code)).toEqual([
      "MPCS 55001-1",
      "MPCS 55001-2",
    ]);
  });

  it("counts only the idle time between classes", () => {
    const at = (day: number, start: number, end: number): Course => ({
      code: `X ${start}-1`,
      name: "x",
      instructor: "x",
      location: "x",
      meetings: [{ day, start, end }],
    });
    expect(gapMinutes([at(0, 540, 600), at(0, 690, 750)])).toBe(90);
    expect(gapMinutes([at(0, 540, 600)])).toBe(0);
    // Back to back is not a gap, and neither is a different day.
    expect(gapMinutes([at(0, 540, 600), at(0, 600, 660)])).toBe(0);
    expect(gapMinutes([at(0, 540, 600), at(1, 690, 750)])).toBe(0);
  });

  it("reports when the node budget ran out instead of hiding it", () => {
    const bounded = searchSchedules(catalog, 3, { limit: 5, nodeBudget: 1 });
    expect(bounded.provenOptimal).toBe(false);
    // An anytime search that answers "nothing" is worse than a slow one.
    expect(bounded.options.length).toBeGreaterThan(0);
  });

  it("terminates on an impossible search instead of hunting forever", () => {
    expect(searchSchedules(catalog, 40, { nodeBudget: 1 }).options).toEqual([]);
  });

  it("rejects a size of zero and an unknown required course", () => {
    expect(() => searchSchedules(catalog, 0)).toThrow(/at least 1/);
    expect(() => searchSchedules(catalog, 2, { required: ["MPCS 99999"] })).toThrow(
      /no course matching/,
    );
    expect(() =>
      searchSchedules(catalog, 2, { required: ["MPCS 55001-1", "MPCS 55001-2"] }),
    ).toThrow(/required twice/);
    expect(() =>
      searchSchedules(catalog, 1, { required: ["MPCS 55001", "MPCS 53001"] }),
    ).toThrow(/do not fit/);
  });

  it("treats a soft day off as a penalty and a strict one as an exclusion", () => {
    // The day comes from the course rather than a constant: which day a given
    // course meets on changes every quarter, and the catalog is refetched.
    const course = catalog.find((c) => c.meetings.length > 0)!;
    const day = course.meetings[0].day;
    const among = [baseCode(course)];

    const soft = solveSchedules(catalog, 1, { among, preferences: { daysOff: [day] } });
    expect(soft[0].breakdown.day_off).toBeGreaterThan(0);

    const strict = solveSchedules(catalog, 1, {
      among,
      preferences: { daysOff: [day], requireDaysOff: true },
    });
    expect(strict).toEqual([]);
  });

  it("leaves out courses with no published meeting time", () => {
    // Such a course conflicts with nothing and scores zero, so left in it
    // outranks every real timetable — the best schedule becomes the one that
    // schedules nothing.
    const unschedulable = QUARTERS.find((q) => q.scheduled < q.courses.length);
    if (!unschedulable) return;

    const mixed = [...scheduledCourses(DEFAULT_QUARTER).slice(0, 6),
                   ...unschedulable.courses.filter((c) => c.meetings.length === 0).slice(0, 6)];

    const honest = searchSchedules(mixed, 3, { limit: 3 });
    expect(honest.unscheduledExcluded).toBe(6);
    expect(honest.options.every((o) => o.cost > 0)).toBe(true);
    expect(
      honest.options.every((o) => o.courses.every((c) => c.meetings.length > 0)),
    ).toBe(true);

    // Opting in reproduces the zero-cost nonsense, on purpose.
    const included = searchSchedules(mixed, 3, { limit: 3, includeUnscheduled: true });
    expect(included.options[0].cost).toBe(0);
    expect(included.unscheduledExcluded).toBe(0);
  });
});

describe("the ranked search index", () => {
  const data = searchIndexData as {
    lengths: Record<string, number>;
    postings: Record<string, Record<string, number>>;
    cases: {
      query: string;
      hits: { url: string; score: number; matched: Record<string, number> }[];
    }[];
  };
  const index = buildIndex(data.postings, data.lengths);

  it("agrees with the Python on every query, scores included", () => {
    for (const testCase of data.cases) {
      const hits = searchIndex(index, testCase.query);
      expect(hits.map((h) => h.url), testCase.query).toEqual(
        testCase.hits.map((h) => h.url),
      );
      hits.forEach((hit, i) => {
        expect(hit.score, testCase.query).toBeCloseTo(testCase.hits[i].score, 6);
        expect(hit.matched, testCase.query).toEqual(testCase.hits[i].matched);
      });
    }
  });

  it("expands a prefix and a wildcard into real terms", () => {
    expect(Object.keys(expandToken(index, "par*")).sort()).toContain("parking");
    expect(Object.keys(expandToken(index, "d?g"))).toEqual(["dog"]);
    expect(expandToken(index, "zebra")).toEqual({});
    expect(expandToken(index, "  ")).toEqual({});
  });

  it("returns nothing when one token of an AND query matches nothing", () => {
    expect(searchIndex(index, "park zebra")).toEqual([]);
    // As an OR query the other token still ranks.
    expect(searchIndex(index, "park zebra", false).length).toBeGreaterThan(0);
  });

  it("does not require every expanded term of a wildcard to be present", () => {
    // "par*" resolves to park, parks, parking. Requiring all three would
    // return nothing; the intent is the one token.
    const hits = searchIndex(index, "par*");
    expect(hits.length).toBeGreaterThan(1);
  });

  it("prefers a short page over a keyword-stuffed long one", () => {
    // /park-hours says "park" 4 times in 32 words; /dog-park-rules says it 5
    // times in 64. Length normalisation is the whole reason it wins.
    const hits = searchIndex(index, "park");
    const rankOf = (url: string) => hits.findIndex((h) => h.url === url);
    expect(rankOf("/park-hours")).toBeLessThan(rankOf("/dog-park-rules"));
  });

  it("prefers matching both terms over stuffing one", () => {
    const hits = searchIndex(index, "park hours");
    expect(hits[0].url).toBe("/park-hours");
    expect(Object.keys(hits[0].matched).sort()).toEqual(["hours", "park"]);
  });

  it("honours the limit", () => {
    expect(searchIndex(index, "par*", true, 2).length).toBe(2);
  });
});

describe("the discard advisor", () => {
  const golden = advisorGolden as {
    cases: {
      label: string;
      hand: { suit: string; rank: string }[];
      currentRank: string;
      currentPoints: number;
      positions: number[];
      expectedPoints: number;
      draws: number;
      exact: boolean;
      probabilityOfScoring: number;
      // Each hand reaches a different set of ranks, so the keys vary per case.
      distribution: Partial<Record<string, number>>;
    }[];
  };

  const toHand = (cards: { suit: string; rank: string }[]): Card[] =>
    cards.map((c) => ({ suit: c.suit as Suit, rank: c.rank as Rank }));

  it("matches the Python on every exactly-computed discard", () => {
    for (const testCase of golden.cases) {
      const hand = toHand(testCase.hand);
      const label = `${testCase.label} ${testCase.positions.join()}`;
      const outcome = evaluateDiscard(hand, testCase.positions);
      expect(outcome.exact, label).toBe(testCase.exact);
      expect(outcome.draws, label).toBe(testCase.draws);
      expect(outcome.expectedPoints, label).toBeCloseTo(
        testCase.expectedPoints,
        9,
      );
      expect(outcome.probabilityOfScoring, label).toBeCloseTo(
        testCase.probabilityOfScoring,
        9,
      );
      expect(outcome.standardError, label).toBe(0);
      for (const [rankName, p] of Object.entries(testCase.distribution)) {
        expect(outcome.distribution[rankName as HandRank], `${label} ${rankName}`)
          .toBeCloseTo(p as number, 9);
      }
    }
  });

  it("agrees with the Python on the current rank of each hand", () => {
    for (const testCase of golden.cases) {
      const hand = toHand(testCase.hand);
      expect(scoreCards(hand)).toBe(testCase.currentRank);
      expect(HAND_SCORES[scoreCards(hand)]).toBe(testCase.currentPoints);
    }
  });

  it("draws from the deck minus the hand, not a fresh deck", () => {
    const hand = toHand(golden.cases[0].hand);
    const pool = unseenCards(hand);
    expect(pool.length).toBe(52 - hand.length);
    const held = new Set(hand.map((c) => `${c.rank}${c.suit}`));
    expect(pool.some((c) => held.has(`${c.rank}${c.suit}`))).toBe(false);
  });

  it("enumerates all 120 legal discards of a seven-card hand", () => {
    const options = allDiscards(7);
    expect(options.length).toBe(120);
    expect(Math.max(...options.map((o) => o.length))).toBe(5);
    expect(options[0]).toEqual([]);
  });

  it("samples above the exact limit and reports an error bar", () => {
    const hand = toHand(golden.cases[0].hand);
    const sampled = evaluateDiscard(hand, [2, 3, 4, 5, 6], 300, mulberry32(7));
    expect(sampled.exact).toBe(false);
    expect(sampled.draws).toBe(300);
    expect(sampled.standardError).toBeGreaterThan(0);
  });

  it("converges on the enumerated truth when it samples", () => {
    // Three discards is 14,190 draws — over the exact limit, so the advisor
    // samples it, but small enough to enumerate here as ground truth.
    const hand = toHand(golden.cases[5].hand);
    const positions = [4, 5, 6];
    const kept = hand.filter((_, i) => !positions.includes(i));
    const pool = unseenCards(hand);

    let sum = 0;
    let n = 0;
    for (let a = 0; a < pool.length; a++) {
      for (let b = a + 1; b < pool.length; b++) {
        for (let c = b + 1; c < pool.length; c++) {
          sum += HAND_SCORES[scoreCards([...kept, pool[a], pool[b], pool[c]])];
          n += 1;
        }
      }
    }
    const truth = sum / n;

    const sampled = evaluateDiscard(hand, positions, 4000, mulberry32(3));
    expect(sampled.exact).toBe(false);
    expect(Math.abs(sampled.expectedPoints - truth)).toBeLessThan(
      4 * sampled.standardError,
    );
  });

  it("keeps four to a flush", () => {
    const hand = toHand(golden.cases[0].hand);
    expect(bestDiscards(hand, 600, 1, mulberry32(1))[0].positions).toEqual([
      4, 5, 6,
    ]);
  });

  it("returns options best first", () => {
    const hand = toHand(golden.cases[5].hand);
    const points = bestDiscards(hand, 200, 10, mulberry32(1)).map(
      (o) => o.expectedPoints,
    );
    expect(points).toEqual([...points].sort((a, b) => b - a));
  });

  it("calls a clear winner a winner and a close call a tie", () => {
    const hand = toHand(golden.cases[0].hand);
    const strong = evaluateDiscard(hand, [4, 5, 6], 3000, mulberry32(5));
    const weak = evaluateDiscard(hand, [0, 1, 2], 3000, mulberry32(5));
    expect(statisticalTies([strong, weak]).length).toBe(1);
    // An option tied with itself is a tie.
    expect(statisticalTies([strong, strong]).length).toBe(2);
    expect(statisticalTies([])).toEqual([]);
  });

  it("keeping everything is exact, needs no draws, and scores the hand", () => {
    const hand = toHand(golden.cases[5].hand);
    const outcome = evaluateDiscard(hand, []);
    expect(outcome.exact).toBe(true);
    expect(outcome.draws).toBe(1);
    expect(outcome.expectedPoints).toBe(HAND_SCORES[scoreCards(hand)]);
  });

  it("rejects an out-of-range position and an over-long discard", () => {
    const hand = toHand(golden.cases[0].hand);
    expect(() => evaluateDiscard(hand, [9])).toThrow(/no card at position/);
    expect(() => evaluateDiscard(hand, [0, 1, 2, 3, 4, 5])).toThrow(/at most/);
  });

  it("parses card shorthand the way the Python does", () => {
    expect(parseCard("Ah")).toEqual({ suit: "hearts", rank: "A" });
    expect(parseCard("10d")).toEqual(parseCard("Td"));
    expect(parseCard("  qc ")).toEqual({ suit: "clubs", rank: "Q" });
    expect(() => parseCard("Ax")).toThrow(/not a suit/);
    expect(() => parseCard("Zs")).toThrow(/not a rank/);
    expect(() => parseCard("h")).toThrow(/not a card/);
  });
});

describe("the bundled MPCS catalog", () => {
  it("carries several quarters, newest first", () => {
    expect(QUARTERS.length).toBeGreaterThanOrEqual(3);
    expect(CATALOG.source).toContain("mpcs-courses.cs.uchicago.edu");
    // Every quarter is labelled and non-empty.
    for (const q of QUARTERS) {
      expect(q.slug, q.label).toMatch(/^\d{4}-\d{2}\/(autumn|winter|spring|summer)$/);
      expect(q.courses.length, q.label).toBeGreaterThan(0);
    }
  });

  it("opens on a quarter that can actually be scheduled", () => {
    // A quarter's course list goes up months before its meeting times do, so
    // the newest quarter is often entirely unschedulable. Opening there would
    // look broken rather than early.
    expect(scheduledCourses(DEFAULT_QUARTER).length).toBeGreaterThanOrEqual(10);
  });

  it("reports how many courses each quarter has scheduled", () => {
    for (const q of QUARTERS) {
      expect(q.scheduled, q.label).toBe(scheduledCourses(q).length);
    }
  });

  it("keeps courses with no published time rather than dropping them", () => {
    // They are still searchable; they just cannot go on a calendar. At least
    // one recent quarter is normally in this state.
    const partial = QUARTERS.filter((q) => q.scheduled < q.courses.length);
    for (const q of partial) {
      expect(q.courses.some((c) => c.meetings.length === 0), q.label).toBe(true);
    }
  });

  it("agrees with the quarter the goldens were generated from", () => {
    // If these drift, the conflict and solver fixtures describe a different
    // catalog than the demo shows.
    expect(coursesGolden.quarter).toBe(CATALOG.default);
  });

  it("was fetched recently enough to be worth calling current", () => {
    const fetched = new Date(CATALOG.fetched);
    expect(Number.isNaN(fetched.getTime())).toBe(false);
    // The refresh action runs weekly; 120 days of slack allows for a pause
    // without turning into a permanently red test.
    const ageDays = (Date.now() - fetched.getTime()) / 86_400_000;
    expect(ageDays).toBeLessThan(120);
  });

  it("looks a quarter up by slug and falls back to the default", () => {
    expect(quarterBySlug(DEFAULT_QUARTER.slug)).toBe(DEFAULT_QUARTER);
    expect(quarterBySlug("1999-00/autumn")).toBe(DEFAULT_QUARTER);
  });
});
