/**
 * Port of `trie_search.trie` (Python) for the browser demo.
 *
 * Kept deliberately close to the original so the two can be compared line by
 * line. `trie.test.ts` checks it against golden fixtures generated by the
 * Python, so a divergence fails a test rather than quietly disagreeing.
 */

import { stem } from "./stem";

export const ALPHABET_SIZE = 26;
export const OTHER = 26;
export const WILDCARD = "?";

const CODE_A = "a".charCodeAt(0);

/** Map a character to [0, 26]. Letters go to 0-25; anything else to 26. */
export function characterToKey(char: string): number {
  if ([...char].length !== 1) {
    throw new Error(`expected a single character, got ${JSON.stringify(char)}`);
  }
  const lowered = char.toLowerCase();
  if (lowered >= "a" && lowered <= "z") return lowered.charCodeAt(0) - CODE_A;
  return OTHER;
}

function indexToChar(index: number): string {
  return index < ALPHABET_SIZE ? String.fromCharCode(index + CODE_A) : "_";
}

export class TrieNode {
  children = new Map<number, TrieNode>();
  isTerminal = false;
  /** The key text as first inserted, so the lossy folding is recoverable. */
  key: string | null = null;
  value: unknown = null;
}

export class Trie {
  readonly root = new TrieNode();
  private count = 0;

  constructor(entries?: Record<string, unknown>) {
    for (const [key, value] of Object.entries(entries ?? {})) this.set(key, value);
  }

  get size(): number {
    return this.count;
  }

  private find(key: string): TrieNode | null {
    let node: TrieNode | undefined = this.root;
    for (const char of key) {
      node = node.children.get(characterToKey(char));
      if (!node) return null;
    }
    return node ?? null;
  }

  set(key: string, value: unknown): void {
    let node = this.root;
    for (const char of key) {
      const index = characterToKey(char);
      let child = node.children.get(index);
      if (!child) {
        child = new TrieNode();
        node.children.set(index, child);
      }
      node = child;
    }
    if (!node.isTerminal) {
      node.isTerminal = true;
      node.key = key;
      this.count += 1;
    }
    node.value = value;
  }

  get(key: string): unknown {
    const node = this.find(key);
    return node?.isTerminal ? node.value : undefined;
  }

  has(key: string): boolean {
    return this.find(key)?.isTerminal ?? false;
  }

  /** Every key, in alphabetical order, in the folded alphabet. */
  *keys(): Generator<string> {
    yield* this.walk(this.root, "");
  }

  private *walk(node: TrieNode, prefix: string): Generator<string> {
    if (node.isTerminal) yield prefix;
    for (const index of [...node.children.keys()].sort((a, b) => a - b)) {
      yield* this.walk(node.children.get(index)!, prefix + indexToChar(index));
    }
  }

  /** Every key beginning with `prefix`. This is what a trie is for. */
  *keysWithPrefix(prefix: string): Generator<string> {
    const node = this.find(prefix);
    if (!node) return;
    const folded = [...prefix].map((c) => indexToChar(characterToKey(c))).join("");
    yield* this.walk(node, folded);
  }

  /** Search with `?` standing for exactly one character. */
  *wildcardSearch(pattern: string): Generator<[string, unknown]> {
    yield* this.match(this.root, "", pattern);
  }

  private *match(
    node: TrieNode,
    prefix: string,
    pattern: string,
  ): Generator<[string, unknown]> {
    if (pattern.length === 0) {
      if (node.isTerminal) yield [prefix, node.value];
      return;
    }
    const char = pattern[0];
    const rest = pattern.slice(1);

    if (char === WILDCARD) {
      for (const index of [...node.children.keys()].sort((a, b) => a - b)) {
        yield* this.match(node.children.get(index)!, prefix + indexToChar(index), rest);
      }
      return;
    }
    const index = characterToKey(char);
    const child = node.children.get(index);
    if (child) yield* this.match(child, prefix + indexToChar(index), rest);
  }

  /** Nodes on the path a key or pattern walks. Drives the visualisation. */
  pathFor(prefix: string): TrieNode[] {
    const path: TrieNode[] = [this.root];
    let node: TrieNode | undefined = this.root;
    for (const char of prefix) {
      node = node.children.get(characterToKey(char));
      if (!node) break;
      path.push(node);
    }
    return path;
  }
}

// ---------------------------------------------------------------------------
// Relevance ranking — port of `trie_search.ranking`
// ---------------------------------------------------------------------------
//
// The trie answers "which words look like this". It cannot answer "how
// important is this word on this page", so searching it returned an
// alphabetical set: a page mentioning "park" once and a park directory
// mentioning it forty times were indistinguishable. BM25 needs three things
// the set could not provide — term frequency, page length, and how many pages
// contain the term at all.

/** Term-frequency saturation. 1.2–2.0 is the usual range. */
export const K1 = 1.5;
/** Length normalisation, 0 (off) to 1 (full). */
export const B = 0.75;

/** Where a term occurs, and how often. URL → occurrences. */
export type Posting = Record<string, number>;

export interface Corpus {
  /** URL → total words on that page. */
  lengths: Record<string, number>;
}

export function corpusSize(corpus: Corpus): number {
  return Object.keys(corpus.lengths).length;
}

export function averageLength(corpus: Corpus): number {
  const urls = Object.keys(corpus.lengths);
  if (urls.length === 0) return 0;
  return urls.reduce((sum, u) => sum + corpus.lengths[u], 0) / urls.length;
}

/**
 * How much a term's presence should count.
 *
 * A word on every page carries no signal. The `1 +` inside the log is what
 * keeps the result non-negative: Robertson's original form,
 * `log((N - df + 0.5) / (df + 0.5))`, goes negative once a term is on more
 * than half the pages, and then a page improves its rank by *not* matching
 * the query. This is the variant Lucene uses for that reason.
 *
 * Given that, `Math.max(…, 0)` only fires when `df > N` -- an index and a
 * corpus that have disagreed. Kept as a guard, not as the thing doing the
 * work.
 */
export function inverseDocumentFrequency(
  size: number,
  documentFrequency: number,
): number {
  if (size === 0 || documentFrequency === 0) return 0;
  const raw = Math.log(
    1 + (size - documentFrequency + 0.5) / (documentFrequency + 0.5),
  );
  return Math.max(raw, 0);
}

/** BM25 contribution of one term to one document. */
export function bm25Score(
  termFrequency: number,
  documentLength: number,
  average: number,
  idf: number,
): number {
  if (termFrequency <= 0 || idf <= 0) return 0;
  if (average <= 0) return idf;
  const normalised = K1 * (1 - B + B * (documentLength / average));
  return (idf * (termFrequency * (K1 + 1))) / (termFrequency + normalised);
}

export interface Hit {
  url: string;
  score: number;
  /** Matched term → occurrences, so a result can explain itself. */
  matched: Record<string, number>;
}

/**
 * Score every page matching at least one term.
 *
 * `requireAll` turns the query from OR into AND, which is what someone typing
 * two words usually means.
 */
export function rank(
  postings: Record<string, Posting>,
  corpus: Corpus,
  requireAll = false,
): Hit[] {
  const terms = Object.keys(postings);
  const size = corpusSize(corpus);
  if (terms.length === 0 || size === 0) return [];

  const average = averageLength(corpus);
  const idfs: Record<string, number> = {};
  for (const term of terms) {
    idfs[term] = inverseDocumentFrequency(
      size,
      Object.keys(postings[term]).length,
    );
  }

  const scores: Record<string, number> = {};
  const matched: Record<string, Record<string, number>> = {};
  for (const term of terms) {
    for (const [url, count] of Object.entries(postings[term])) {
      const length = corpus.lengths[url] ?? 0;
      scores[url] =
        (scores[url] ?? 0) + bm25Score(count, length, average, idfs[term]);
      matched[url] = { ...(matched[url] ?? {}), [term]: count };
    }
  }

  let urls = Object.keys(scores);
  if (requireAll) {
    urls = urls.filter((u) => Object.keys(matched[u]).length === terms.length);
  }

  // Score descending, then URL, so equal scores order deterministically —
  // matching the Python's `(-score, url)` sort key exactly.
  return urls
    .map((url) => ({
      url,
      score: Math.round(scores[url] * 1e6) / 1e6,
      matched: matched[url],
    }))
    .sort((a, b) => b.score - a.score || (a.url < b.url ? -1 : a.url > b.url ? 1 : 0));
}

// ---------------------------------------------------------------------------
// The ranked index — port of `trie_search.crawler.SearchIndex`
// ---------------------------------------------------------------------------

export interface SearchIndex {
  /** Term → (URL → occurrences). */
  postings: Record<string, Posting>;
  corpus: Corpus;
  /** Trie over the vocabulary, for prefix and wildcard expansion. */
  trie: Trie;
}

export function buildIndex(
  postings: Record<string, Posting>,
  lengths: Record<string, number>,
): SearchIndex {
  return {
    postings,
    corpus: { lengths },
    trie: new Trie(Object.fromEntries(Object.keys(postings).map((t) => [t, t]))),
  };
}

/**
 * Resolve one query token into the concrete terms it matches.
 *
 * A bare word is exact, `?` is a single-character wildcard, and a trailing
 * `*` is a prefix. Expansion happens here so the scorer only ever sees real
 * terms.
 */
export function expandToken(
  index: SearchIndex,
  token: string,
): Record<string, Posting> {
  const t = token.trim().toLowerCase();
  if (!t) return {};

  const found: Record<string, Posting> = {};
  if (t.includes("?")) {
    for (const [term] of index.trie.wildcardSearch(t)) {
      if (term in index.postings) found[term] = index.postings[term];
    }
    return found;
  }
  if (t.endsWith("*")) {
    for (const term of index.trie.keysWithPrefix(t.slice(0, -1))) {
      if (term in index.postings) found[term] = index.postings[term];
    }
    return found;
  }
  return t in index.postings ? { [t]: index.postings[t] } : {};
}

/**
 * Rank pages for a whitespace-separated query.
 *
 * `requireAll` defaults to true: someone typing two words almost always means
 * both, and an OR search buries the good hits under pages that only matched
 * the commoner word.
 */
export function searchIndex(
  index: SearchIndex,
  query: string,
  requireAll = true,
  limit = 20,
): Hit[] {
  const tokens = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (tokens.length === 0) return [];

  const postings: Record<string, Posting> = {};
  let matchedTokens = 0;
  for (const token of tokens) {
    const expanded = expandToken(index, token);
    if (Object.keys(expanded).length > 0) matchedTokens += 1;
    Object.assign(postings, expanded);
  }

  // A token nothing matches means the AND can never be satisfied.
  if (requireAll && matchedTokens < tokens.length) return [];

  // A wildcard token expands to many terms, so requiring every *term* to be
  // present would be wrong; the intent is every *token*. The two coincide
  // only when each token resolved to exactly one term.
  const strict =
    requireAll && tokens.length === Object.keys(postings).length;
  return rank(postings, index.corpus, strict).slice(0, limit);
}

// --------------------------------------------------------------------------- //
// Positions, phrases, and indexing text in the browser
// --------------------------------------------------------------------------- //

/**
 * Ported from `systems/trie-search`. The demo indexes text you paste rather
 * than crawling, because a static page cannot fetch arbitrary sites — but
 * everything downstream of the tokenizer is the same code path the command
 * line runs, and `trie.test.ts` checks it against fixtures the Python wrote.
 */

/** Stripped from the ends of a token; internal punctuation is kept, so
 *  "well-known" stays one word while a bare "--" is dropped entirely. */
const PUNCTUATION = ".,;:!?()[]{}<>\"'`—–-_*|/\\";

/** Split text into lowercase words, dropping punctuation-only tokens. */
export function tokenize(text: string): string[] {
  const out: string[] = [];
  for (const raw of text.split(/\s+/)) {
    let word = raw.toLowerCase();
    let start = 0;
    let end = word.length;
    while (start < end && PUNCTUATION.includes(word[start])) start += 1;
    while (end > start && PUNCTUATION.includes(word[end - 1])) end -= 1;
    word = word.slice(start, end);
    if (word) out.push(word);
  }
  return out;
}

/** Term → URL → ascending word offsets. */
export type Positions = Record<string, Record<string, number[]>>;

export interface BuiltIndex extends SearchIndex {
  positions: Positions;
  stemmed: boolean;
  /** Stem → the surface forms it came from, so results can show real words. */
  surfaces: Record<string, string[]>;
  tokens: number;
}

/**
 * Index documents given as text. `documents` maps a label to its content.
 *
 * Positions are always recorded here. The command line makes them optional
 * because a large crawl pays for them in memory; a few pasted paragraphs does
 * not, and phrase search is half the point of the demo.
 */
export function buildFromDocuments(
  documents: Record<string, string>,
  stemming = false,
): BuiltIndex {
  const postings: Record<string, Posting> = {};
  const positions: Positions = {};
  const lengths: Record<string, number> = {};
  const surfaces: Record<string, Set<string>> = {};
  let tokens = 0;

  for (const [label, text] of Object.entries(documents)) {
    const words = tokenize(text);
    lengths[label] = words.length;
    tokens += words.length;
    words.forEach((surface, offset) => {
      const term = stemming ? stem(surface) : surface;
      if (stemming) {
        (surfaces[term] ??= new Set()).add(surface);
      }
      ((positions[term] ??= {})[label] ??= []).push(offset);
      const posting = (postings[term] ??= {});
      posting[label] = (posting[label] ?? 0) + 1;
    });
  }

  return {
    postings,
    positions,
    corpus: { lengths },
    trie: new Trie(Object.fromEntries(Object.keys(postings).map((t) => [t, t]))),
    stemmed: stemming,
    surfaces: Object.fromEntries(
      Object.entries(surfaces).map(([k, v]) => [k, [...v].sort()]),
    ),
    tokens,
  };
}

/** How many times the terms appear consecutively, in order, in one document. */
export function phraseMatches(
  positions: Positions,
  terms: string[],
  url: string,
): number {
  if (terms.length === 0) return 0;
  const first = positions[terms[0]]?.[url];
  if (!first) return 0;
  const later = terms.slice(1).map((t) => new Set(positions[t]?.[url] ?? []));
  let hits = 0;
  for (const start of first) {
    if (later.every((seen, i) => seen.has(start + i + 1))) hits += 1;
  }
  return hits;
}

/**
 * Score documents containing the exact phrase, treating it as a single term.
 *
 * Summing the words' individual BM25 scores would rank a page saying "park"
 * forty times and "hours" thirty times above one that actually contains the
 * phrase — which is the bug this exists to avoid.
 */
export function rankPhrase(
  index: BuiltIndex,
  terms: string[],
  limit = 20,
): Hit[] {
  if (terms.length === 0) return [];
  if (terms.some((t) => !(t in index.postings))) return [];

  let candidates = new Set(Object.keys(index.postings[terms[0]]));
  for (const term of terms.slice(1)) {
    const next = new Set(Object.keys(index.postings[term]));
    candidates = new Set([...candidates].filter((u) => next.has(u)));
  }

  const counts: Record<string, number> = {};
  for (const url of candidates) {
    const n = phraseMatches(index.positions, terms, url);
    if (n > 0) counts[url] = n;
  }
  if (Object.keys(counts).length === 0) return [];

  const phrase = terms.join(" ");
  const size = corpusSize(index.corpus);
  const idf = inverseDocumentFrequency(size, Object.keys(counts).length);
  const average = averageLength(index.corpus);
  const hits: Hit[] = Object.entries(counts).map(([url, count]) => ({
    url,
    score: Number(
      bm25Score(count, index.corpus.lengths[url] ?? 0, average, idf).toFixed(6),
    ),
    matched: { [phrase]: count },
  }));
  hits.sort((a, b) => b.score - a.score || a.url.localeCompare(b.url));
  return hits.slice(0, limit);
}

/** The words inside double quotes, or null if the query is not a phrase. */
export function quotedTerms(query: string): string[] | null {
  const text = query.trim();
  if (text.length >= 2 && text.startsWith('"') && text.endsWith('"')) {
    return text.slice(1, -1).toLowerCase().split(/\s+/).filter(Boolean);
  }
  return null;
}

/**
 * Search a browser-built index, handling quoted phrases and stemming.
 *
 * Kept separate from `searchIndex` so the existing golden-fixture tests keep
 * exercising the original path unchanged.
 */
export function searchBuilt(
  index: BuiltIndex,
  query: string,
  requireAll = true,
  limit = 20,
): Hit[] {
  const phrase = quotedTerms(query);
  if (phrase !== null) {
    const terms = index.stemmed ? phrase.map(stem) : phrase;
    if (terms.length === 1) {
      return searchIndex(index, terms[0], requireAll, limit);
    }
    return rankPhrase(index, terms, limit);
  }
  if (!index.stemmed) return searchIndex(index, query, requireAll, limit);

  // A stemmed index holds roots, so fold the query too -- but leave wildcards
  // alone, since they are patterns over the stored keys.
  const folded = query
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean)
    .map((t) => (t.includes("?") || t.endsWith("*") ? t : stem(t)))
    .join(" ");
  return searchIndex(index, folded, requireAll, limit);
}
